# numpy crash course 8th nov

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [7]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# creating arrays

In [7]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [9]:
type(my_list)

list

In [17]:
arr = np.array(my_list)

In [19]:
arr

array([0, 1, 2, 3, 4, 5])

In [15]:
type(my_list)

list

In [19]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
np.arange(3.0)

array([0., 1., 2.])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
np.arange(20,10)

array([], dtype=int32)

In [31]:
np.arange(-20,10)


array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [33]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [35]:
np.arange(-16,-10)

array([-16, -15, -14, -13, -12, -11])

In [37]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [39]:
np.arange(10,10)

array([], dtype=int32)

In [41]:
np.arange(10,30,4)

array([10, 14, 18, 22, 26])

In [43]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [45]:
np.zeros(6) # parameter tunning

array([0., 0., 0., 0., 0., 0.])

In [47]:
np.zeros(5,dtype = int) # hyperparameter tunning

array([0, 0, 0, 0, 0])

In [49]:
np.ones(5,dtype = int)

array([1, 1, 1, 1, 1])

In [51]:
np.zeros((2,2),dtype = int)

array([[0, 0],
       [0, 0]])

In [55]:
zero = np.zeros([2,2])
print(zero)

print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [59]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [61]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [63]:
np.ones(4,dtype = int)

array([1, 1, 1, 1])

In [67]:
range(5)

range(0, 5)

In [69]:
r = range(5)
r

range(0, 5)

In [71]:
for i in r:
    print(i)

0
1
2
3
4


In [79]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
list(range(1,10,3))

[1, 4, 7]

In [92]:
np.random.rand(5)

array([0.39862977, 0.0624075 , 0.92096235, 0.73940057, 0.42628232])

In [96]:
np.random.rand(2,4)

array([[0.06033416, 0.71868145, 0.3272326 , 0.1781837 ],
       [0.68395856, 0.06959077, 0.2545569 , 0.9319601 ]])

In [106]:
np.random.randint(2,4)

3

In [114]:
np.random.randint(20,100,5)

array([68, 87, 72, 96, 49])

In [116]:
np.random.randint(0,1)

0

In [125]:
np.random.randint((2,4))

array([0, 3])

In [127]:
np.random.randint(10,30,(10,10))

array([[28, 26, 13, 12, 15, 21, 29, 24, 22, 11],
       [20, 20, 25, 29, 25, 25, 27, 21, 15, 27],
       [20, 27, 15, 26, 18, 25, 25, 18, 23, 25],
       [10, 18, 20, 23, 18, 16, 29, 16, 26, 27],
       [26, 17, 19, 16, 22, 25, 23, 14, 14, 22],
       [27, 29, 28, 23, 19, 23, 19, 25, 18, 13],
       [26, 24, 15, 19, 11, 29, 12, 29, 18, 27],
       [10, 14, 20, 13, 26, 28, 26, 11, 29, 18],
       [20, 14, 23, 10, 28, 16, 13, 28, 19, 18],
       [25, 19, 25, 24, 25, 15, 24, 20, 29, 28]])

In [137]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 16, 17, 19],
       [14, 12, 19, 17],
       [16, 18, 19, 18],
       [15, 17, 14, 13],
       [18, 18, 12, 16]])

In [139]:
type(b)

numpy.ndarray

In [141]:
b

array([[17, 16, 17, 19],
       [14, 12, 19, 17],
       [16, 18, 19, 18],
       [15, 17, 14, 13],
       [18, 18, 12, 16]])

In [143]:
b[:]

array([[17, 16, 17, 19],
       [14, 12, 19, 17],
       [16, 18, 19, 18],
       [15, 17, 14, 13],
       [18, 18, 12, 16]])

In [145]:
b[4:]

array([[18, 18, 12, 16]])

In [147]:
b[1:3]

array([[14, 12, 19, 17],
       [16, 18, 19, 18]])

In [149]:
b[1,3]

17

In [151]:
b[0:-2]

array([[17, 16, 17, 19],
       [14, 12, 19, 17],
       [16, 18, 19, 18]])